src/Entity/Cart.php
<?php

namespace App\Entity;

use App\Repository\CartRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Factory\UuidFactory;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: CartRepository::class)]
class Cart
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $uuid = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateIn = null;

    #[ORM\Column(length: 12)]
    private ?string $ipIn = null;

    #[ORM\ManyToOne(inversedBy: 'carts')]
    private ?User $User = null;

    #[ORM\Column(length: 255)]
    private ?string $origine = null;

    #[ORM\Column(length: 255)]
    private ?string $statut = null;

    #[ORM\Column(nullable: true)]
    private ?int $prix = null;

    #[ORM\Column(nullable: true)]
    private ?int $dureeEstimee = null;


    public function __construct()
    {
        $this->uuid = Uuid::v4();
        $this->dateIn = new \DateTimeImmutable();
        $this->ipIn = $_SERVER["REMOTE_ADDR"];
        $this->statut = "NEW";

    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function getDateIn(): ?\DateTimeInterface
    {
        return $this->dateIn;
    }

    public function getIpIn(): ?string
    {
        return $this->ipIn;
    }

    public function getUser(): ?User
    {
        return $this->User;
    }

    public function setUser(?User $User): self
    {
        $this->User = $User;

        return $this;
    }

    public function getOrigine(): ?string
    {
        return $this->origine;
    }

    public function setOrigine(string $origine): self
    {
        $this->origine = $origine;

        return $this;
    }

    public function getStatut(): ?string
    {
        return $this->statut;
    }

    public function setStatut(string $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(?int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDureeEstimee(): ?int
    {
        return $this->dureeEstimee;
    }

    public function setDureeEstimee(?int $dureeEstimee): self
    {
        $this->dureeEstimee = $dureeEstimee;

        return $this;
    }
}

templates/front/connexion.html.twig
{% extends 'base.html.twig' %}

{% set bodycss = "overflow-y-hidden" %}
{% set noHeaderBG = true %}
{% set noDivBG = true %}
{% set noNav = true %}
{% block headercss %}absolute z-50 w-full{% endblock %}

{% block body %}
    <div class="flex justify-center h-screen bg-cover bg-center bg-no-repeat" style="background-image:url('{{ asset('build/static/bg_1.jpg') }}')">
        <div data-aos="fade-up" data-aos-easing="ease-in-out" data-aos-duration="1000" class="flex items-center w-full max-w-md px-6 mx-auto lg:w-2/6">
                <div class="flex-1">
                    <div class="text-center">
                        {% if error | default(false) and app.session.get("loginFailedCompteur") < 5 and app.session.get("loginFailedCompteur") > 0  %}
                            <div id="alert-2" class="flex p-4 mb-14 bg-red-100 rounded-lg dark:bg-red-200" role="alert">
                                <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5 text-red-700 dark:text-red-800" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                                <span class="sr-only">Info</span>
                                <div class="ml-3 text-sm font-medium text-red-700 dark:text-red-800">
                                    Tentative restante: {{ app.session.get("loginFailedCompteur") }}/5
                                </div>
                                <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-red-100 text-red-500 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-red-200 dark:text-red-600 dark:hover:bg-red-300" data-dismiss-target="#alert-2" aria-label="Close">
                                    <span class="sr-only">Close</span>
                                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                                </button>
                            </div>
                        {% endif %}
                        {% if error | default(false) and app.session.get("loginFailedCompteur") == 0 %}
                            <div id="alert-2" class="flex p-4 mb-14 bg-red-200 rounded-lg dark:bg-red-200" role="alert">
                                <svg aria-hidden="true" class="flex-shrink-0 w-5 h-5 text-red-700 dark:text-red-800" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clip-rule="evenodd"></path></svg>
                                <span class="sr-only">Info</span>
                                <div class="ml-3 text-sm font-medium text-red-700 dark:text-red-800">
                                    <span>Votre compte à été bloqué.</span>
                                </div>
                                <button type="button" class="ml-auto -mx-1.5 -my-1.5 bg-red-200 text-red-500 hover:bg-red-300 rounded-lg focus:ring-2 focus:ring-red-400 p-1.5 hover:bg-red-200 inline-flex h-8 w-8 dark:bg-red-200 dark:text-red-600 dark:hover:bg-red-300 duration-300" data-dismiss-target="#alert-2" aria-label="Close">
                                    <span class="sr-only">Close</span>
                                    <svg class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
                                </button>
                            </div>
                        {% endif %}
                        <h2 class="font-prata leading-[35px] tracking-[4px] text-3xl font-bold">SE CONNECTER</h2>
                        <p class="mt-2 text-sm text-black/40 tracking-[2px]">Ravi de vous revoir !</p>
                    </div>
                <div class="mt-8">
                    <form method="post">
                        <div>
                            <label for="email" class="block mb-2 text-[12px] font-semibold tracking-[1.5px]">Adresse-Mail</label>
                            <input type="email" name="email" id="email" value="{{ lastMail }}" placeholder="example@example.com" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white" />
                        </div>
                        <div class="mt-6">
                            <div class="flex justify-between mb-2">
                                <label for="password" class="text-[12px] font-semibold tracking-[1.5px]">Mot de passe</label>
                                <a href="#" class="text-sm text-gray-400 hover:text-white hover:underline">Mot de passe oublié ?</a>
                            </div>

                            <input type="password" name="password" id="password" placeholder="**********" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white"/>
                        </div>

                        <div class="mt-6">
                            <button
                                    class="w-full px-4 py-2 tracking-[2px] text-white transition-colors transform bg-[#cca688] rounded-full hover:bg-[#8e6f57] focus:outline-none focus:bg-blue-400 focus:ring focus:ring-blue-300 focus:ring-opacity-50 duration-300">
                                Connexion
                            </button>
                        </div>
                    </form>
                    <p class="mt-6 text-sm text-center tracking-[1px] text-black/50">Vous n'avez pas de compte ?<a href="{{ path('app_register') }}" class="pl-2 text-[#cca688] focus:outline-none focus:underline hover:underline hover:scale-105">Inscrivez-vous</a>.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/profil.html.twig
{% extends 'base.html.twig' %}

{% set noHeaderBG = true %}
{% set noDivBG = true %}
{% block headercss %}{% endblock %}

{% block body %}
    <main class="flex w-full">
        <section class="w-2/5 h-[90vh]">
            <div class="relative w-[150px] h-[150px] mt-[30px] mb-[15px] mx-auto bg-white drop-shadow-xl rounded-full text-center">
                <span class="absolute top-1/2 -translate-y-[44%] -translate-x-[48%] text-[56px] font-prata font-medium uppercase">{{ app.user.email[0:1] }}</span>
            </div>
            <div class="w-[160px] mx-auto">
                <h3 class="font-medium uppercase">{{ app.user.email }}</h3>
                <span class="text-red-500 text-sm">Compte non vérifié !</span>
            </div>
            <div>
                <a></a>
                <a></a>
            </div>
        </section>
        <section class="w-full h-[90vh]">
            <div data-controller="lazyload" data-src="https://institutlea.fx.salle2reunion.com/form/testpartial">

            </div>
        </section>
    </main>
{% endblock %}

templates/front/register.html.twig
{% extends 'base.html.twig' %}

{% set bodycss = "overflow-y-hidden" %}
{% set noHeaderBG = true %}
{% set noDivBG = true %}
{% set noNav = true %}
{% block headercss %} absolute z-50 w-full {% endblock %}

{% block body %}
    <div class="flex justify-center h-screen bg-cover bg-center bg-no-repeat" style="background-image:url('{{ asset('build/static/bg_1.jpg') }}')">
        <div data-aos="fade-up" data-aos-easing="ease-in-out"  data-aos-duration="1000" class="flex items-center w-full max-w-md px-6 mx-auto my-auto lg:w-2/6">
            <div class="flex-1">
                <div class="text-center">
                    <h2 class="font-prata leading-[35px] tracking-[4px] text-3xl font-bold">S'ENREGISTRER</h2>
                    <p class="mt-2 text-sm text-black/40 tracking-[2px]">L'équipe vous souhaite la bienvenue !</p>
                </div>
                <div class="mt-8">
                    <form method="post">
                        {% if errorsMail | length > 0 %}
                            <div>
                                <label for="email" class="block mb-2 text-xs leading-[22px] tracking-[1.5px]">Adresse-Mail</label>
                                <input type="email" name="email" id="email" value="{{ lastMail | default("") }}" placeholder="example@example.com" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border-2 border-red-500 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white" />
                                {% for errorMail in errorsMail %}
                                    <label for="email" class="block mb-2 text-xs text-red-500 leading-[22px] tracking-[1.5px]">{{ errorMail }}</label>
                                {% endfor %}
                            </div>
                        {% else %}
                        <div>
                            <label for="email" class="block mb-2 text-xs leading-[22px] tracking-[1.5px]">Adresse-Mail</label>
                            <input type="email" name="email" id="email" value="{{ lastMail | default("") }}" placeholder="example@example.com" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white" />
                        </div>
                        {% endif %}
                        {% if errorsPwd | length > 0 %}
                            <div class="mt-6">
                                <div class="flex justify-between mb-2">
                                    <label for="password" class="text-xs leading-[22px] tracking-[1.5px]">Mot de passe</label>
                                </div>
                                <input type="password" name="password" id="password" placeholder="**********" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border-2 border-red-500 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white"/>
                                <label for="password" class="text-xs text-red-500 leading-[22px] tracking-[1.5px]">Le mot de passe doit être minimum de 8 caractères et doit contenir une majuscule, minuscule et 1 chiffre</label>
                            </div>
                            <div class="mt-6">
                                <div class="flex justify-between mb-2">
                                    <label for="password" class="text-xs leading-[22px] tracking-[1.5px]">Confirmer mot de passe</label>
                                </div>
                                <input type="password" name="passwordC" id="passwordC" placeholder="**********" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border-2 border-red-500 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white"/>
                                <label for="password" class="text-xs text-red-500 leading-[22px] tracking-[1.5px]">Le mot de passe doit être minimum de 8 caractères et doit contenir une majuscule, minuscule et 1 chiffre</label>
                            </div>
                        {% else %}
                            <div class="mt-6">
                                <div class="flex justify-between mb-2">
                                    <label for="password" class="text-xs leading-[22px] tracking-[1.5px]">Mot de passe</label>
                                </div>
                                <input type="password" name="password" id="password" placeholder="**********" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white"/>
                            </div>
                            <div class="mt-6">
                                <div class="flex justify-between mb-2">
                                    <label for="password" class="text-xs leading-[22px] tracking-[1.5px]">Confirmer mot de passe</label>
                                </div>
                                <input type="password" name="passwordC" id="passwordC" placeholder="**********" class="block w-full px-4 py-2 mt-2 text-gray-700 placeholder-gray-400/50 bg-white border border-gray-200 rounded-md focus:border-blue-400 focus:ring-blue-400 focus:outline-none focus:ring focus:ring-opacity-40 focus:placeholder-white"/>
                            </div>
                        {% endif %}
                        <div class="mt-6">
                            <button
                                    class="w-full px-4 py-2 tracking-[2px] text-white transition-colors transform bg-[#cca688] rounded-full hover:bg-[#8e6f57] focus:outline-none focus:bg-blue-400 focus:ring focus:ring-blue-300 focus:ring-opacity-50 duration-300">
                                S'inscrire
                            </button>
                        </div>
                    </form>

                    <p class="mt-6 text-sm text-center tracking-[1px] text-black/50">Déjà un compte ?<a href="{{ path('app_connexion') }}" class="pl-2 text-[#cca688] focus:outline-none focus:underline hover:underline hover:scale-105">Connectez-vous</a>.</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/front/reservatonPresta.html.twig
{% extends 'base.html.twig' %}

{% set noHeaderBG = true %}
{% set noDivBG = true %}
{% block headercss %}{% endblock %}
{% block nav %}flex justify-between w-3/5 other:w-4/5 h-[70px] mx-auto items-center phone:w-11/12{% endblock %}

{% block body %}
    <main class="w-3/5 mx-auto">
        {#<div class="flex items-center w-4/5 p-10 mt-[30px] mb-[50px] mx-auto space-x-1 text-black/60">
            <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M15.2084 9.16665C15.2084 12.5 10.0001 16.0416 10.0001 16.0416C10.0001 16.0416 4.79175 12.5 4.79175 9.16665C4.79175 6.24998 7.23866 3.95831 10.0001 3.95831C12.7615 3.95831 15.2084 6.24998 15.2084 9.16665Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke:currentColor;"></path><path d="M11.875 9.16669C11.875 10.2022 11.0355 11.0417 10 11.0417C8.96447 11.0417 8.125 10.2022 8.125 9.16669C8.125 8.13115 8.96447 7.29169 10 7.29169C11.0355 7.29169 11.875 8.13115 11.875 9.16669Z" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" data-darkreader-inline-stroke="" style="--darkreader-inline-stroke:currentColor;"></path></svg>
            <a class="tracking-[1px] underline" href="https://www.google.fr/maps/place/4+Rue+de+la+Lombardie,+78930+Guerville/@48.9446059,1.7350433,19.68z/data=!4m5!3m4!1s0x47e6bde331c09e37:0xb3d8831241fedb4c!8m2!3d48.9444497!4d1.7353126">4 Rue De La Lombardie, 78930 Guerville</a>
        </div>#}
        <div class="relative w-full p-10 mt-[50px] mb-[20px]">
            <h3 class="text-[#cca688]/80 font-prata font-semibold text-[20px] tracking-[2px]">1. <span class="text-black/80">Sélection de la prestation</span></h3>
            <div class="bg-white p-5 mt-[30px] drop-shadow-xl rounded-md">
                <section class="">
                    <h4 class="text-sm font-medium tracking-[1px]">{{ prestation.label }}</h4>
                    <div class="flex justify-between items-center text-[13px] text-black/80 font-semibold tracking-[0.5px] mt-1">
                        <div class="flex">
                            <span class="">{{ prestation.duree }}</span>
                            <div class="absolute right-5 top-[37%]">
                                <a href="#" class="text-sm font-medium text-[#cca688] tracking-[0.5px] hover:underline hover:text-red-500 cursor-pointer duration-300">Supprimer</a>
                            </div>
                            <span class="flex items-center before:content-[''] before:block before:w-[4px] before:h-[4px] before:bg-black/40 before:rounded-full before:ml-1.5 before:mr-1.5">{{ prestation.prix }} €</span>
                        </div>
                    </div>
                </section>
            </div>
        </div>
        <div class="w-full p-10 mb-[50px] mx-auto">
            <h3 class="text-[#cca688]/80 font-prata font-semibold text-[20px] tracking-[2px]">2. <span class="text-black/80">Choix du créneau</span></h3>
            <div class="mt-[30px] py-[20px] bg-white drop-shadow-xl">
                <div class="flex w-full mx-auto">
                    {#{% for date in allDate|slice(0, 5) %}
                        <div class='relative bg-[#cca688] shadow-lg rounded-lg content-center justify-center'>
                            <span class="flex h-3 w-3 absolute -top-1 -right-1">
                                <span class="animate-ping absolute group-hover:opacity-75 opacity-0 inline-flex h-full w-full rounded-full bg-[#cca688]"></span>
                                <span class="relative inline-flex rounded-full h-3 w-3 bg-[#8e6f57]"></span>
                            </span>
                            <p class='text-white/90 text-sm'>ab</p>
                        </div>
                    {% endfor %}#}
                </div>
            </div>
        </div>
        <div class="carousel w-full">
            <div id="slide1" class="carousel-item relative w-full">
                <div class="flex w-4/5 mx-auto bg-indigo-500 rounded-md space-x-10">
                    {% for date in allDate|slice(0, 5) %}
                        <div class='relative w-24 h-16 bg-[#cca688] shadow-lg rounded-lg content-center justify-center'>
                            <span class="flex h-3 w-3 absolute -top-1 -right-1">
                                <span class="animate-ping absolute group-hover:opacity-75 opacity-0 inline-flex h-full w-full rounded-full bg-[#cca688]"></span>
                                <span class="relative inline-flex rounded-full h-3 w-3 bg-[#8e6f57]"></span>
                            </span>
                            <p class='text-white/90 text-sm'>ab</p>
                        </div>
                    {% endfor %}
                </div>
                <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                    <a href="#slide4" class="btn btn-circle">❮</a>
                    <a href="#slide2" class="btn btn-circle">❯</a>
                </div>
            </div>
            <div id="slide2" class="carousel-item relative w-full">
                <img src="https://placeimg.com/800/200/arch" class="w-full" />
                <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                    <a href="#slide1" class="btn btn-circle">❮</a>
                    <a href="#slide3" class="btn btn-circle">❯</a>
                </div>
            </div>
            <div id="slide3" class="carousel-item relative w-full">
                <img src="https://placeimg.com/800/200/arch" class="w-full" />
                <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                    <a href="#slide2" class="btn btn-circle">❮</a>
                    <a href="#slide4" class="btn btn-circle">❯</a>
                </div>
            </div>
            <div id="slide4" class="carousel-item relative w-full">
                <img src="https://placeimg.com/800/200/arch" class="w-full" />
                <div class="absolute flex justify-between transform -translate-y-1/2 left-5 right-5 top-1/2">
                    <a href="#slide3" class="btn btn-circle">❮</a>
                    <a href="#slide1" class="btn btn-circle">❯</a>
                </div>
            </div>
        </div>
    </main>

{% endblock %}